[tool.black]
line_length = 100

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
combine_as_imports = true
skip = [".git", "cdk.out", "venv"]

[tool.flake8]
extend-ignore = ["E203"]
exclude = [".git", "venv", "cdk.out", "__pycache__"]
max-complexity = 10
max-line-length = 100
