name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: lambda

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag proton-carddav-lambda:$(date +%s)
